FBMS2.Web/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Authorization;

using FBMS2.Core.Models;
using FBMS2.Core.Services;
using FBMS2.Core.Security;
using FBMS2.Web.ViewModels;
using FBMS2.Data.Services;
using FBMS2.Data.Repositories;

namespace FBMS2.Web.Controllers
{
    [Authorize]
    //stock controller inherits the properties from the base controller
    public class StockController : BaseController
    {
        private readonly IUserService service;

        public StockController(IUserService ss)
        {
            service = ss;
        }

        public IActionResult Index()
        {
            var stock = service.GetAllStock();

            return View(stock);
        }

        //GET - get a stock item by using the id of the stock item
        public IActionResult Details(int id)
        {
            var stockitem = service.GetStockById(id);
            if (stockitem == null)
            {
                Alert ("Item Not Found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            return View(stockitem);
        }

        //display blank form to create the item of stock
        public IActionResult Create()
        {
            //return a blank form for the user to fill out and add stock
            return View();
        }

        //POST - Create the item of stock
        [HttpPost]
        public IActionResult Create([Bind("UserId, Description, Quantity, ExpiryDate")] Stock s)
        {
            if(ModelState.IsValid)
            {
                s = service.AddStock(s.UserId, s.Description, s.Quantity, s.ExpiryDate);

                Alert($"Stock item added successfully", AlertType.success);

                return RedirectToAction(nameof(Details));
            }

            return View(s);

        }

        [HttpPost]
        public IActionResult Edit(int id)
        {
            var s = service.GetStockById(id);

            if (s == null)
            {
                Alert($"Stock {id} not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            return View(s);
        }

        [HttpPost]
        public IActionResult Edit(int id, [Bind("Id, Description, Quantity, ExpiryDate")] Stock s)
        {
            if(ModelState.IsValid)
            {
                service.UpdateStock(s);
                Alert("Stock updated successfully", AlertType.info);

                return RedirectToAction(nameof(Details), new { Id = s.Id});
            }

            return View(s);
        }

        public IActionResult Delete(int id)
        {
            var s = service.GetStockById(id);

            if (s == null)
            {
                Alert($"Vehicle{id} not found", AlertType.warning);
                return RedirectToAction(nameof(Index));
            }

            return View(s);
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            service.DeleteStockById(id);

            Alert("Vehicle deleted successfully", AlertType.info);

            return RedirectToAction(nameof(Index));
        }
    }
}

FBMS2.Web/Views/Shared/_Alert.cshtml
<!-- AMC - alert partial to display any alerts via layout fbms2 -->
@{
    var message = TempData["Alert.Message"] ?? null;
    var type    = TempData["Alert.Type"]    ?? null;
}
@if (message != null)
{
    <div class="alert alert-@type" role="alert">
        @message
    </div>
}

FBMS2.Web/Views/Shared/_BreadCrumbs.cshtml
@model IList<(string,string)>

@if (Model != null ) {
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      @foreach(var (link,crumb) in Model)
      {
          @if (link == null || link.Length == 0)
          {
              <li class="breadcrumb-item active" aria-current="page">@crumb</li>
          }
          else
          {
              <li class="breadcrumb-item"><a href="@link">@crumb</a></li>
          }
      }
    </ol>
  </nav>
}

FBMS2.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FBMS2.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FBMS2.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Sample.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex" id="navbarNavAltMarkup">
                                       
                    <div class="navbar-nav flex-grow-1">
                        <a class="nav-link text-dark active" asp-controller="Home" asp-action="Index">Home</a>
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        <a class="nav-link text-dark" asp-controller="Stock" asp-action="Index">Stock Management</a>    
                        <a class="nav-link text-dark" asp-controller="Home" asp-action="Secure">Secure</a>
                    </div>         

                    <!-- AMC The login partial is added here for authentication flex-sm-row-reverse-->
                    <partial name="_LoginPartial" />      
                    
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        
        <!-- AMC Any alert defined in controller is rendered here -->
        <partial name="_Alert" />

        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Sample.Web - <a asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>